name: Build, Test, and Release Docker Image

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  IMAGE_NAME: dpci-ansible-image
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/dpci-ansible-image

jobs:
  build-and-test:
    name: Build & Smoke-Test
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.generate_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate tag (only on main)
        id: generate_tag
        if: github.ref == 'refs/heads/main'
        run: |
          latest_tag=$(git tag -l 'v0.0.*' | sort -V | tail -n1)
          if [ -z "$latest_tag" ]; then
            next_tag="v0.0.1"
          else
            patch=$(echo $latest_tag | cut -d. -f3)
            next_tag="v0.0.$((patch + 1))"
          fi
          echo "tag=$next_tag" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (linux/amd64 only for local test)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME }}:local
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}

      - name: Smoke Test
        run: |
          docker run --rm dpci-ansible-image:local sh -c "echo ✅ Shell OK"
          docker run --rm dpci-ansible-image:local ansible --version
          docker run --rm dpci-ansible-image:local pre-commit --version

  tag-and-push:
    name: Release Multi-Arch Image
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ needs.build-and-test.outputs.image-tag }}
            ${{ env.DOCKERHUB_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          tag="${{ needs.build-and-test.outputs.image-tag }}"
          if git tag | grep -q "^$tag$"; then
            echo "Tag already exists, skipping."
            exit 1
          fi

          git tag "$tag"
          git push origin "$tag"
